[update-gogs-repos] Updated.

diff --git a/link/.local/bin/update-gogs-repos b/link/.local/bin/update-gogs-repos
--- a/link/.local/bin/update-gogs-repos
+++ b/link/.local/bin/update-gogs-repos
@@ -5,36 +5,39 @@ GOGS_USER=gnidmoo
 # Add gogs to repositories
 for i in $(find . -maxdepth 1 -type d -print | sed 's/^\.\///')
 do
-	cd "/home/${USER}/rendu/$i"
-	if [ -d .git ] && [ -n "$(git remote -v | grep epitech)" ]
+	if [ "$i" != "." ]
 	then
-		echo "Trying to add 'gogs' remote in $(basename $(pwd))..."
-		git remote remove origin
-		git remote add origin git@git.epitech.eu:/${USER}/$(basename $(pwd))
-		
-		# Add 'gogs' remote to gogs repos
-		gogs_repo="$(basename $(pwd) | tr '[:upper:]' '[:lower:]').git"
-		push="$(git push gogs@git.gnidmoo.tk:$GOGS_USER/$gogs_repo master 2>&1)"
-		if [ -z "$(echo "$push" "=>" "$?" | grep Gogs)" ]
+		cd "$(pwd)/$i"
+		if [ -d .git ] && [ -n "$(git remote -v | grep epitech)" ]
 		then
-			echo "Gogs repo found in" $(pwd)
-			git remote set-url --add --push origin git@git.epitech.eu:/${USER}/$(basename $(pwd))
-			git remote set-url --add --push origin gogs@git.gnidmoo.tk:$GOGS_USER/$(echo $(basename $(pwd)) | tr '[:upper:]' '[:lower:]').git
-			
-			echo -n "Trying to push to 'origin'... "
-			push_code="$(git push -u origin master > /dev/null 2>&1 && echo $?)"
-			if [ "$push_code" == "0" ]
+			echo "Trying to add 'gogs' remote in $(basename $(pwd))..."
+			git remote remove origin
+			git remote add origin git@git.epitech.eu:/${USER}/$(basename $(pwd))
+
+			# Add 'gogs' remote to gogs repos
+			gogs_repo="$(basename $(pwd) | tr '[:upper:]' '[:lower:]').git"
+			push="$(git push gogs@git.gnidmoo.tk:$GOGS_USER/$gogs_repo master 2>&1)"
+			if [ -z "$(echo "$push" "=>" "$?" | grep Gogs)" ]
 			then
-				echo "OK."
+				echo "Gogs repo found in" $(pwd)
+				git remote set-url --add --push origin git@git.epitech.eu:/${USER}/$(basename $(pwd))
+				git remote set-url --add --push origin gogs@git.gnidmoo.tk:$GOGS_USER/$(echo $(basename $(pwd)) | tr '[:upper:]' '[:lower:]').git
+
+				echo -n "Trying to push to 'origin'... "
+				push_code="$(git push -u origin master > /dev/null 2>&1 && echo $?)"
+				if [ "$push_code" == "0" ]
+				then
+					echo "OK."
+				else
+					echo "Failed with code $push_code."
+				fi
 			else
-				echo "Failed with code $push_code."
+				echo "$(pwd) is not a Gogs repo"
 			fi
 		else
-			echo "$(pwd) is not a Gogs repo"
+			echo "$(pwd) is not an Epitech repo"
 		fi
-	else
-		echo "$(pwd) is not an Epitech repo"
+		echo
+		cd ..
 	fi
-	echo
-	cd ..
 done
